=== dgeissl/jakarta-cactus/documentation/docs/dtds/navigation-v10.dtd
<!--
 * ========================================================================
 * 
 * Copyright 2001-2003 The Apache Software Foundation.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *   http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * 
 * ========================================================================
-->

<!-- ===================================================================

     Apache Cactus Navigation DTD (Version 1.0)

PURPOSE:
  This DTD defines the structure of Navigation files which need to
  exist in every directory of the documentation to determine the
  navigation menu items.

TYPICAL INVOCATION:

  <!DOCTYPE navigation PUBLIC
       "-//Apache Software Foundation//DTD Cactus Navigation V1.0//EN"
       "navigation-v10.dtd">

==================================================================== -->

<!-- =============================================================== -->
<!-- Navigation -->
<!-- =============================================================== -->

<!ELEMENT navigation (menu*)>
<!ATTLIST navigation
    title CDATA #REQUIRED
    index CDATA #REQUIRED
>

<!ELEMENT menu (menu|item)*>
<!ATTLIST menu
    id ID #IMPLIED
    label CDATA #REQUIRED
>

<!ELEMENT item EMPTY>
<!ATTLIST item
    id ID #REQUIRED
    label CDATA #IMPLIED
>

=== dgeissl/jakarta-cactus/documentation/docs/xdocs/participating/navigation.xml
<?xml version="1.0"?>
<!DOCTYPE navigation
  PUBLIC "-//Apache Software Foundation//DTD Cactus Navigation V1.0//EN"
  "file:../../dtds/navigation-v10.dtd">

<navigation title="Participating" index="participating">

  <menu label="Participating">
    <item id="participating" label="Introduction"/>
    <item id="contributors"/>
    <item id="users"/>
  </menu>

  <menu label="Developers">
    <item id="coding_conventions"/>
    <item id="coverage"/>
    <item id="howto_build"/>
    <item id="todo"/>
    <item id="release_checklist"/>
  </menu>

  <menu label="Miscellaneous">
    <item id="logos"/>
  </menu>

</navigation>

=== dgeissl/jakarta-cactus/documentation/docs/xdocs/navigation.xml
<?xml version="1.0"?>
<!DOCTYPE navigation PUBLIC
  "-//Apache Software Foundation//DTD Cactus Navigation V1.0//EN"
  "file:../dtds/navigation-v10.dtd">

<navigation>

  <menu label="About">
    <item id="index"/>
    <item id="news"/>
    <item id="changes"/>
    <item id="features"/>
    <item id="goals"/>
    <item id="todo"/>
    <item label="Contributors" id="contributors"/>
    <item label="Contributing" id="contributing"/>
    <item label="Cactus Users" id="users"/>
    <item label="Tested on ..." id="testedon"/>
    <item label="License" id="license"/>
  </menu>

  <menu label="Downloads">
    <item label="Downloads" id="downloads"/>
  </menu>

  <menu label="Documentation">
    <item label="How it works?" id="how_it_works"/>
    <item label="Getting Started" id="getting_started"/>
    <item label="Mock vs Container" id="mockobjects"/>
    <item label="Javadocs" id="javadoc"/>
    <item label="FAQ" id="faq"/>
  </menu>

  <menu label="Howto Guides">
    <item label="Classpath Howto" id="howto_classpath"/>
    <item label="Config Howto" id="howto_config"/>
    <item label="Migration Howto" id="howto_migration"/>

    <!-- TestCase tutorials -->
    <item label="TestCase Howto" id="howto_testcase"/>

    <item label="Jsp Howto" id="howto_jsp"/>
    <item label="Runner Howto" id="howto_runner"/>
    <item label="Security Howto" id="howto_security"/>


    <item label="HttpUnit Howto" id="howto_httpunit"/>
    <item label="Sample Howto" id="howto_sample"/>

    <!-- EJB tutorial -->
    <item label="EJB Howto" id="howto_ejb"/>

    <!-- IDE tutorials -->
    <item label="IDE Howto" id="howto_ide"/>

    <item label="Tomcat Howto" id="howto_tomcat"/>

    <item label="JUnitEE Howto" id="howto_junitee"/>
  </menu>

  <menu label="Integration">
    <item label="Ant" id="howto_ant"/>
    <item label="Eclipse" id="eclipse_plugin"/>
  </menu>

  <menu label="Support">
    <item label="Bug database" id="bug_database"/>
    <item label="Mailing list" id="mailinglist"/>
  </menu>

  <menu label="Misc.">
    <item label="Why the name?" id="cactusname"/>
    <item label="Logo Challenge" id="logos"/>
    <item label="Resources" id="resources"/>
    <item label="Test Coverage" id="coverage"/>
    <item label="Stats" id="stats"/>
  </menu>

  <menu label="Developers">
    <item label="CVS" id="cvs"/>
    <item label="Coding Conventions" id="coding_conventions"/>
    <item label="Build results" id="build_result"/>
    <item label="Release Checklist" id="release_checklist"/>
    <item label="Build from sources" id="howto_build"/>
  </menu>

  <menu label="Translations">
    <item label="Korean" id="korean"/>
    <item label="Japanese" id="japanese"/>
  </menu>

</navigation>

=== dgeissl/jakarta-cactus/cactus-site/src/site/xdoc/integration/navigation.xml
<?xml version="1.0"?>
<!DOCTYPE navigation
  PUBLIC "-//Apache Software Foundation//DTD Cactus Navigation V1.0//EN"
  "file:../../dtds/navigation-v10.dtd">

<navigation title="Running Tests" index="howto_runner">

  <menu label="Main Page" id="index"/>

  <menu label="Running Tests">
    <item id="howto_runner" label="Overview"/>
  </menu>

  <menu label="Integrations">
    <item id="integration_manual" label="Manual"/>
    <item id="integration_ant" label="Ant"/>
    <item id="integration_eclipse" label="Eclipse"/>
    <item id="integration_jetty" label="Jetty"/>
    <item id="integration_browser" label="Browser"/>
    <item id="howto_tomcat" label="Tomcat"/>
    <item id="integration_maven" label="Maven"/>
    <item id="howto_ide" label="Various IDEs"/>
    <item id="howto_junitee" label="JUnitEE"/>
  </menu>

</navigation>
